### PR TITLE
pull upstream 2020-08-18

### PR DESCRIPTION
**Pull request by fisx**

### CODE REVIEW

**Comment by fisx** [comment]
We've long been depending on this, but it's much clearer if we have this on (our own) master.  Also we don't risk loosing the branch.

**Comment by fisx** [comment]
CLAssistant warnings can be ignored (this is contribution to an outside project, even if it happens in a weird way).

**Comment by fisx** [comment]
**PLEASE DO NOT DELETE THIS BRANCH!!**

**Comment by tiago-loureiro** [comment]
@fisx You've been busy :P

**Pull request merged**
